name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 15 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
      
    - name: Login IBM Cloud
      run: |
        ./IBM_Cloud_CLI/ibmcloud login -u ${{ secrets.MAIL }} -p ${{ secrets.PWD }} -r ${{ secrets.RGN }}
        
    - name: Restart
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g Default
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf restart ${{ secrets.CFNAME }}
